Repository bakdata/kpops, pull requests merged in 2023-08, with the labels that each got.

#292 Validate unique step names
  kpops/cli/main.py
  kpops/pipeline_generator/pipeline.py
  tests/pipeline/resources/no-input-topic-pipeline/pipeline.yaml
  tests/pipeline/resources/pipeline-duplicate-step-names/pipeline.yaml
  tests/pipeline/snapshots/snap_test_pipeline.py
  tests/pipeline/test_components/components.py
  tests/pipeline/test_pipeline.py
Labels: type/bug, component/generator

#306 Refactor CLI using dtyper
  docs/docs/user/references/cli-commands.md
  kpops/__init__.py
  kpops/cli/main.py
  kpops/pipeline_generator/pipeline.py
  poetry.lock
  pyproject.toml
  tests/pipeline/test_pipeline.py
Labels: type/refactor, component/cli

#308 Remove camel case conversion of internal models
  docs/docs/resources/pipeline-components/kafka-app.yaml
  docs/docs/resources/pipeline-components/kafka-connector.yaml
  docs/docs/resources/pipeline-components/kafka-sink-connector.yaml
  docs/docs/resources/pipeline-components/kafka-source-connector.yaml
  docs/docs/resources/pipeline-components/kubernetes-app.yaml
  docs/docs/resources/pipeline-components/pipeline.yaml
  docs/docs/resources/pipeline-components/producer.yaml
  docs/docs/resources/pipeline-components/streams-app.yaml
  docs/docs/resources/pipeline-defaults/defaults-kafka-connector.yaml
  docs/docs/resources/pipeline-defaults/defaults-kafka-source-connector.yaml
  docs/docs/resources/pipeline-defaults/defaults-kubernetes-app.yaml
  docs/docs/resources/pipeline-defaults/defaults.yaml
  docs/docs/schema/config.json
  docs/docs/schema/pipeline.json
  docs/docs/user/references/defaults.md
  kpops/cli/pipeline_config.py
  kpops/component_handlers/helm_wrapper/model.py
  kpops/component_handlers/topic/model.py
  kpops/components/base_components/kafka_connector.py
  kpops/components/base_components/kubernetes_app.py
  kpops/components/base_components/models/to_section.py
  kpops/components/base_components/pipeline_component.py
  kpops/components/streams_bootstrap/producer/producer_app.py
  kpops/components/streams_bootstrap/streams/streams_app.py
  tests/cli/snapshots/snap_test_schema_generation.py
  tests/pipeline/resources/defaults.yaml
  tests/pipeline/resources/pipeline-with-env-defaults/defaults.yaml
  tests/pipeline/snapshots/snap_test_example.py
  tests/pipeline/snapshots/snap_test_pipeline.py
Labels: component/pipeline-components, breaking-change

#307 Automatically support schema generation for custom components
  docs/docs/schema/config.json
  docs/docs/schema/pipeline.json
  hooks/gen_schema.py
  kpops/components/base_components/base_defaults_component.py
  kpops/components/base_components/kafka_app.py
  kpops/components/base_components/kafka_connector.py
  kpops/components/base_components/kubernetes_app.py
  kpops/components/base_components/pipeline_component.py
  kpops/components/streams_bootstrap/producer/producer_app.py
  kpops/components/streams_bootstrap/streams/streams_app.py
  kpops/utils/gen_schema.py
  kpops/utils/pydantic.py
  tests/cli/snapshots/snap_test_schema_generation.py
  tests/cli/test_schema_generation.py
Labels: type/enhancement, component/pipeline-components

#301 Migrate to asyncio
  kpops/cli/main.py
  kpops/component_handlers/kafka_connect/connect_wrapper.py
  kpops/component_handlers/kafka_connect/kafka_connect_handler.py
  kpops/component_handlers/kafka_connect/timeout.py
  kpops/component_handlers/schema_handler/schema_handler.py
  kpops/component_handlers/topic/handler.py
  kpops/component_handlers/topic/proxy_wrapper.py
  kpops/components/base_components/kafka_app.py
  kpops/components/base_components/kafka_connector.py
  kpops/components/base_components/kubernetes_app.py
  kpops/components/base_components/pipeline_component.py
  kpops/components/streams_bootstrap/producer/producer_app.py
  kpops/components/streams_bootstrap/streams/streams_app.py
  poetry.lock
  pyproject.toml
  tests/component_handlers/kafka_connect/test_connect_handler.py
  tests/component_handlers/kafka_connect/test_connect_wrapper.py
  tests/component_handlers/schema_handler/test_schema_handler.py
  tests/component_handlers/topic/test_proxy_wrapper.py
  tests/component_handlers/topic/test_topic_handler.py
  tests/components/test_kafka_app.py
  tests/components/test_kafka_sink_connector.py
  tests/components/test_kafka_source_connector.py
  tests/components/test_kubernetes_app.py
  tests/components/test_producer_app.py
  tests/components/test_streams_app.py
Labels: type/refactor

#313 Set default for ToSection topics
  docs/docs/resources/pipeline-components/kafka-app.yaml
  docs/docs/resources/pipeline-components/kafka-connector.yaml
  docs/docs/resources/pipeline-components/kafka-sink-connector.yaml
  docs/docs/resources/pipeline-components/kafka-source-connector.yaml
  docs/docs/resources/pipeline-components/kubernetes-app.yaml
  docs/docs/resources/pipeline-components/pipeline.yaml
  docs/docs/resources/pipeline-components/producer.yaml
  docs/docs/resources/pipeline-components/streams-app.yaml
  docs/docs/schema/pipeline.json
  kpops/components/base_components/models/to_section.py
  tests/cli/snapshots/snap_test_schema_generation.py
Labels: type/refactor, component/pipeline-components

#309 Derive component type automatically from class name
  docs/docs/resources/pipeline-components/pipeline.yaml
  docs/docs/resources/pipeline-components/producer.yaml
  docs/docs/resources/pipeline-defaults/defaults-producer.yaml
  docs/docs/resources/pipeline-defaults/defaults.yaml
  docs/docs/schema/pipeline.json
  docs/docs/user/references/components.md
  docs/docs/user/references/defaults.md
  docs/docs/user/what-is-kpops.md
  examples/bakdata/atm-fraud-detection/defaults.yaml
  examples/bakdata/atm-fraud-detection/pipeline.yaml
  kpops/cli/registry.py
  kpops/components/base_components/base_defaults_component.py
  kpops/components/base_components/kafka_app.py
  kpops/components/base_components/kafka_connector.py
  kpops/components/base_components/kubernetes_app.py
  kpops/components/base_components/pipeline_component.py
  kpops/components/streams_bootstrap/producer/model.py
  kpops/components/streams_bootstrap/producer/producer_app.py
  kpops/components/streams_bootstrap/streams/streams_app.py
  kpops/pipeline_generator/pipeline.py
  kpops/utils/__init__.py
  kpops/utils/gen_schema.py
  kpops/utils/pydantic.py
  setup.cfg
  tests/cli/snapshots/snap_test_schema_generation.py
  tests/cli/test_registry.py
  tests/cli/test_schema_generation.py
  tests/compiler/resources/defaults_development.yaml
  tests/components/test_base_defaults_component.py
  tests/pipeline/resources/custom-config/pipeline.yaml
  tests/pipeline/resources/defaults.yaml
  tests/pipeline/resources/no-topics-defaults/defaults.yaml
  tests/pipeline/resources/pipeline-component-should-have-prefix/pipeline.yaml
  tests/pipeline/resources/pipeline-with-env-defaults/defaults.yaml
  tests/pipeline/resources/pipeline-with-paths/pipeline.yaml
  tests/pipeline/resources/read-from-component/pipeline.yaml
  tests/pipeline/snapshots/snap_test_example.py
  tests/pipeline/snapshots/snap_test_pipeline.py
  tests/pipeline/test_components/__init__.py
  tests/pipeline/test_components/components.py
  tests/pipeline/test_components_without_schema_handler/__init__.py
  tests/pipeline/test_components_without_schema_handler/components.py
  tests/utils/test_pydantic.py
Labels: type/enhancement, component/pipeline-components, breaking-change

#315 Annotate types for ToSection models mapping
  docs/docs/schema/pipeline.json
  kpops/component_handlers/schema_handler/schema_provider.py
  kpops/components/base_components/models/__init__.py
  kpops/components/base_components/models/to_section.py
  tests/cli/resources/module.py
  tests/cli/snapshots/snap_test_schema_generation.py
  tests/component_handlers/schema_handler/resources/module.py
  tests/pipeline/test_components/components.py
Labels: type/refactor, component/pipeline-components

#319 Refactor handling of Helm flags
  docs/docs/schema/config.json
  docs/docs/schema/pipeline.json
  docs/docs/user/references/cli-commands.md
  kpops/cli/main.py
  kpops/component_handlers/helm_wrapper/model.py
  kpops/components/base_components/kafka_connector.py
  kpops/components/base_components/kubernetes_app.py
  kpops/components/base_components/pipeline_component.py
  kpops/components/streams_bootstrap/producer/producer_app.py
  kpops/components/streams_bootstrap/streams/streams_app.py
  tests/components/test_kafka_app.py
  tests/components/test_kubernetes_app.py
  tests/pipeline/resources/custom-config/config.yaml
  tests/pipeline/test_template.py
Labels: type/refactor, component/handlers, component/cli, component/pipeline-components, component/config

#300 Add flag to exclude pipeline steps
  actions/kpops-runner/README.md
  actions/kpops-runner/action.yaml
  docs/docs/user/references/cli-commands.md
  kpops/cli/main.py
  tests/cli/test_pipeline_steps.py
Labels: type/enhancement, component/cli

#266 Update the variable documentation
  .github/workflows/ci.yaml
  .pre-commit-config.yaml
  docs/docs/dev/development/autogeneration.md
  docs/docs/resources/variables/cli_env_vars.env
  docs/docs/resources/variables/cli_env_vars.md
  docs/docs/resources/variables/config_env_vars.env
  docs/docs/resources/variables/config_env_vars.md
  docs/docs/resources/variables/variable_substitution.yaml
  docs/docs/user/references/variables.md
  docs/docs/user/references/variables/environment_variables.md
  docs/docs/user/references/variables/substitution.md
  docs/mkdocs.yml
  hooks/gen_docs/__init__.py
  hooks/gen_docs/gen_docs_env_vars.py
  kpops/utils/dict_ops.py
  poetry.lock
  pyproject.toml
  tests/pipeline/resources/pipeline-substitution/pipeline.yaml
Labels: area/documentation

#232 Refactor input/output types
  docs/docs/resources/pipeline-components/kafka-app.yaml
  docs/docs/resources/pipeline-components/kafka-connector.yaml
  docs/docs/resources/pipeline-components/kafka-sink-connector.yaml
  docs/docs/resources/pipeline-components/kafka-source-connector.yaml
  docs/docs/resources/pipeline-components/kubernetes-app.yaml
  docs/docs/resources/pipeline-components/pipeline.yaml
  docs/docs/resources/pipeline-components/producer-app.yaml
  docs/docs/resources/pipeline-components/sections/from_.yaml
  docs/docs/resources/pipeline-components/sections/to.yaml
  docs/docs/resources/pipeline-components/streams-app.yaml
  docs/docs/resources/pipeline-defaults/defaults-kafka-connector.yaml
  docs/docs/resources/pipeline-defaults/defaults-kubernetes-app.yaml
  docs/docs/resources/pipeline-defaults/defaults.yaml
  docs/docs/schema/pipeline.json
  examples/bakdata/atm-fraud-detection/defaults.yaml
  examples/bakdata/atm-fraud-detection/pipeline.yaml
  kpops/components/base_components/models/from_section.py
  kpops/components/base_components/models/to_section.py
  kpops/components/base_components/pipeline_component.py
  kpops/components/streams_bootstrap/streams/model.py
  kpops/components/streams_bootstrap/streams/streams_app.py
  tests/cli/snapshots/snap_test_schema_generation.py
  tests/components/test_kafka_sink_connector.py
  tests/components/test_producer_app.py
  tests/components/test_streams_app.py
  tests/pipeline/resources/no-input-topic-pipeline/pipeline.yaml
  tests/pipeline/resources/pipeline-with-short-topics/defaults.yaml
  tests/pipeline/resources/pipeline-with-short-topics/pipeline.yaml
  tests/pipeline/snapshots/snap_test_example.py
  tests/pipeline/snapshots/snap_test_pipeline.py
  tests/pipeline/test_components/components.py
  tests/pipeline/test_pipeline.py
Labels: type/refactor, breaking-change

#273 Fix editor integration example in docs
  docs/docs/resources/editor_integration/settings.json
Labels: area/documentation

#325 Add KPOps Runner GitHub Action to the documentation
  actions/kpops-runner/README.md
  docs/docs/user/references/ci-integration/github-actions.md
  docs/mkdocs.yml
Labels: area/documentation

#322 Refactor Kafka Connect handler
  docs/docs/schema/pipeline.json
  kpops/component_handlers/kafka_connect/connect_wrapper.py
  kpops/component_handlers/kafka_connect/kafka_connect_handler.py
  kpops/component_handlers/kafka_connect/model.py
  kpops/components/base_components/kafka_connector.py
  kpops/utils/pydantic.py
  tests/cli/test_pipeline_steps.py
  tests/component_handlers/kafka_connect/test_connect_handler.py
  tests/component_handlers/kafka_connect/test_connect_wrapper.py
  tests/components/test_kafka_connector.py
  tests/components/test_kafka_sink_connector.py
  tests/components/test_kafka_source_connector.py
  tests/pipeline/resources/defaults.yaml
  tests/pipeline/snapshots/snap_test_example.py
  tests/pipeline/snapshots/snap_test_pipeline.py
  tests/pipeline/test_components_without_schema_handler/components.py
Labels: type/refactor, component/handlers, component/pipeline-components

#324 Remove `:type` and `:rtype` from docstrings
  docs/docs/schema/pipeline.json
  hooks/gen_schema.py
  kpops/component_handlers/helm_wrapper/helm.py
  kpops/component_handlers/helm_wrapper/helm_diff.py
  kpops/components/base_components/base_defaults_component.py
  kpops/components/base_components/kafka_app.py
  kpops/components/base_components/kafka_connector.py
  kpops/components/base_components/kubernetes_app.py
  kpops/components/base_components/models/from_section.py
  kpops/components/base_components/models/to_section.py
  kpops/components/base_components/pipeline_component.py
  kpops/components/streams_bootstrap/producer/model.py
  kpops/components/streams_bootstrap/producer/producer_app.py
  kpops/components/streams_bootstrap/streams/model.py
  kpops/components/streams_bootstrap/streams/streams_app.py
  kpops/pipeline_generator/pipeline.py
  kpops/utils/dict_ops.py
  kpops/utils/docstring.py
  kpops/utils/gen_schema.py
  kpops/utils/yaml_loading.py
  tests/cli/test_schema_generation.py
Labels: area/documentation

#334 Fix optional flags in GitHub action
  actions/kpops-runner/README.md
  actions/kpops-runner/action.yaml
  docs/docs/user/references/ci-integration/github-actions.md
Labels: type/bug, area/CI

#329 Break the documentation down into smaller subsection
  docs/docs/images/kpops-components_class-diagram.drawio
  docs/docs/images/kpops-components_class-diagram.png
  docs/docs/resources/architecture/components-hierarchy.md
  docs/docs/resources/pipeline-config/config.yaml
  docs/docs/user/core-concepts/components/kafka-app.md
  docs/docs/user/core-concepts/components/kafka-connector.md
  docs/docs/user/core-concepts/components/kafka-sink-connector.md
  docs/docs/user/core-concepts/components/kafka-source-connector.md
  docs/docs/user/core-concepts/components/kubernetes-app.md
  docs/docs/user/core-concepts/components/overview.md
  docs/docs/user/core-concepts/components/producer-app.md
  docs/docs/user/core-concepts/components/streams-app.md
  docs/docs/user/core-concepts/config.md
  docs/docs/user/core-concepts/defaults.md
  docs/docs/user/core-concepts/variables/environment_variables.md
  docs/docs/user/core-concepts/variables/substitution.md
  docs/docs/user/examples/atm-fraud-pipeline.md
  docs/docs/user/getting-started/quick-start.md
  docs/docs/user/getting-started/teardown.md
  docs/docs/user/references/components.md
  docs/docs/user/references/config.md
  docs/docs/user/references/editor-integration.md
  docs/docs/user/what-is-kpops.md
  docs/mkdocs.yml
Labels: area/documentation

#342 Lint GitHub action
  .github/workflows/lint.yaml
Labels: area/CI

#340 Fix GitHub action error in non-Python projects
  actions/kpops-runner/action.yaml
Labels: type/bug, area/CI

#332 Exclude abstract components from pipeline schema
  docs/docs/schema/pipeline.json
  kpops/components/base_components/kafka_app.py
  kpops/components/base_components/pipeline_component.py
  kpops/utils/gen_schema.py
  tests/cli/resources/empty_module.py
  tests/cli/test_schema_generation.py
Labels: component/pipeline-components

#337 Add `dprint` as the markdown formatter
  .github/workflows/ci.yaml
  .pre-commit-config.yaml
  README.md
  docs/docs/dev/development/autogeneration.md
  docs/docs/developer/auto-generation.md
  docs/docs/developer/formatting.md
  docs/docs/resources/architecture/components-hierarchy.md
  docs/docs/resources/examples/defaults.md
  docs/docs/resources/examples/pipeline.md
  docs/docs/resources/pipeline-components/pipeline.md
  docs/docs/resources/pipeline-defaults/defaults.md
  docs/docs/user/core-concepts/components/kafka-app.md
  docs/docs/user/core-concepts/components/kafka-sink-connector.md
  docs/docs/user/core-concepts/components/kafka-source-connector.md
  docs/docs/user/core-concepts/components/kubernetes-app.md
  docs/docs/user/core-concepts/components/producer-app.md
  docs/docs/user/core-concepts/components/streams-app.md
  docs/docs/user/core-concepts/config.md
  docs/docs/user/core-concepts/defaults.md
  docs/docs/user/core-concepts/variables/environment_variables.md
  docs/docs/user/core-concepts/variables/substitution.md
  docs/docs/user/examples/atm-fraud-pipeline.md
  docs/docs/user/getting-started/quick-start.md
  docs/docs/user/getting-started/setup.md
  docs/docs/user/getting-started/teardown.md
  docs/docs/user/references/editor-integration.md
  docs/docs/user/what-is-kpops.md
  docs/mkdocs.yml
  dprint.json
Labels: area/documentation

#339 Publish pre-release docs for PRs & main branch
  .github/actions/update-docs/action.yml
  .github/workflows/ci.yaml
  .github/workflows/release.yaml
  justfile
Labels: area/documentation, area/CI

#343 Fix GitHub ref variable for pushing docs to main branch
  .github/workflows/ci.yaml
Labels: type/bug

#345 Align docs colours
  docs/docs/overrides/home.html
  docs/docs/resources/setup/kafka.yaml
  docs/docs/stylesheets/extra.css
  docs/docs/user/getting-started/setup.md
  docs/docs/user/references/editor-integration.md
  docs/mkdocs.yml
Labels: area/documentation

#346 Fix versioning of docs when releasing
  .github/actions/update-docs/action.yml
Labels: type/bug, area/CI

#349 Simplify deployment with local Helm charts
  docs/docs/schema/pipeline.json
  kpops/component_handlers/helm_wrapper/helm.py
  kpops/components/base_components/kafka_app.py
  kpops/components/base_components/kubernetes_app.py
  tests/components/test_kubernetes_app.py
Labels: type/refactor

#350 Print only rendered templates when `--template` flag is set
  kpops/cli/main.py
  tests/pipeline/test_pipeline.py
Labels: type/bug

#352 Add migration guide
  docs/docs/user/migration-guide/v1-v2.md
  docs/mkdocs.yml
Labels: area/documentation
