Repository bakdata/kpops, pull requests merged in 2023-07, with the labels that each got.

#279 Update KPOps runner readme for dev versions
  actions/kpops-runner/README.md
Labels: area/documentation, low-prio

#280 Add breaking changes section to change log config
  .github/changelog-config.json
Labels: area/CI

#278 Plural broker field in pipeline config
  config.yaml
  docs/docs/resources/pipeline-components/kafka-app.yaml
  docs/docs/resources/pipeline-components/pipeline.yaml
  docs/docs/resources/pipeline-components/producer.yaml
  docs/docs/resources/pipeline-components/streams-app.yaml
  docs/docs/resources/pipeline-defaults/defaults-kafka-app.yaml
  docs/docs/resources/pipeline-defaults/defaults.yaml
  docs/docs/resources/pipeline_config/config.yaml
  docs/docs/schema/config.json
  examples/bakdata/atm-fraud-detection/config.yaml
  examples/bakdata/atm-fraud-detection/defaults.yaml
  kpops/cli/pipeline_config.py
  kpops/components/base_components/kafka_connector.py
  tests/components/test_kafka_sink_connector.py
  tests/components/test_kafka_source_connector.py
  tests/pipeline/resources/custom-config/config.yaml
  tests/pipeline/resources/defaults.yaml
  tests/pipeline/resources/kafka-connect-sink-config/config.yaml
  tests/pipeline/resources/no-topics-defaults/defaults.yaml
  tests/pipeline/resources/pipeline-component-should-have-prefix/defaults.yaml
  tests/pipeline/resources/pipeline-with-env-defaults/defaults.yaml
Labels: type/refactor, component/config, breaking-change

#255 Reactivate Windows CI
  .github/workflows/ci.yaml
  poetry.lock
  pyproject.toml
  tests/cli/test_schema_generation.py
  tests/component_handlers/kafka_connect/test_connect_wrapper.py
Labels: area/CI

#286 Downgrade Poetry version on the Windows CI pipeline
  .github/workflows/ci.yaml
Labels: area/CI

#276 Remove workaround for pipeline steps
  kpops/cli/main.py
  tests/cli/test_pipeline_steps.py
Labels: type/refactor

#289 Set ANSI theme for output of `kpops generate`
  kpops/pipeline_generator/pipeline.py
Labels: component/cli

#293 Exclude Helm tests from dry-run diff
  kpops/component_handlers/helm_wrapper/exception.py
  kpops/component_handlers/helm_wrapper/helm.py
  kpops/component_handlers/helm_wrapper/model.py
  tests/component_handlers/helm_wrapper/test_helm_wrapper.py
  tests/components/test_kubernetes_app.py
Labels: type/bug

#294 Update Black
  .pre-commit-config.yaml
  poetry.lock
  pyproject.toml
Labels: area/dependencies

#295 Fix vulnerability in mkdocs-material
  poetry.lock
Labels: area/dependencies

#290 Order PipelineComponent fields
  docs/docs/schema/pipeline.json
  kpops/components/base_components/base_defaults_component.py
  kpops/components/base_components/kubernetes_app.py
  kpops/components/base_components/pipeline_component.py
  kpops/pipeline_generator/pipeline.py
  tests/cli/snapshots/snap_test_schema_generation.py
Labels: type/refactor, component/pipeline-components

#302 Migrate requests to httpx
  kpops/cli/main.py
  kpops/component_handlers/kafka_connect/connect_wrapper.py
  kpops/component_handlers/kafka_connect/exception.py
  kpops/component_handlers/topic/exception.py
  kpops/component_handlers/topic/proxy_wrapper.py
  kpops/component_handlers/utils/exception.py
  poetry.lock
  pyproject.toml
  tests/component_handlers/kafka_connect/test_connect_wrapper.py
  tests/component_handlers/topic/test_proxy_wrapper.py
Labels: type/refactor
