Repository bakdata/kpops, pull requests merged in 2023-06, with the labels that each got.

#230 Fix missing extra input topics
  docs/docs/schema/pipeline.json
  examples/bakdata/atm-fraud-detection/defaults.yaml
  examples/bakdata/atm-fraud-detection/pipeline.yaml
  kpops/component_handlers/kafka_connect/connect_wrapper.py
  kpops/component_handlers/kafka_connect/kafka_connect_handler.py
  kpops/component_handlers/topic/handler.py
  kpops/component_handlers/topic/proxy_wrapper.py
  kpops/components/base_components/kubernetes_app.py
  poetry.lock
  pyproject.toml
  tests/cli/snapshots/snap_test_schema_generation.py
  tests/components/test_streams_app.py
  tests/pipeline/snapshots/snap_test_example.py
Labels: type/bug

#236 Add background to docs home page
  README.md
  docs/docs/assets/images/kpops-background.svg
  docs/mkdocs.yml
  docs/overrides/home.html
Labels: area/documentation

#237 add --namespace option to Helm template command
  kpops/component_handlers/helm_wrapper/helm.py
  kpops/components/base_components/kafka_connector.py
  kpops/components/base_components/kubernetes_app.py
  tests/component_handlers/helm_wrapper/test_helm_wrapper.py
  tests/pipeline/test_template.py
Labels: type/bug, component/generator

#238 Add missing type annotation for Pydantic attributes
  kpops/component_handlers/helm_wrapper/model.py
  kpops/components/base_components/kafka_app.py
  kpops/components/base_components/kafka_connector.py
  kpops/components/base_components/kubernetes_app.py
  kpops/components/base_components/pipeline_component.py
  kpops/components/streams_bootstrap/producer/model.py
  kpops/components/streams_bootstrap/streams/model.py
  kpops/utils/docstring.py
Labels: type/bug

#198 Refactor variable substitution
  examples/bakdata/atm-fraud-detection/defaults.yaml
  kpops/component_handlers/helm_wrapper/helm.py
  kpops/components/base_components/base_defaults_component.py
  kpops/components/base_components/kafka_app.py
  kpops/components/base_components/kafka_connector.py
  kpops/components/base_components/kubernetes_app.py
  kpops/components/base_components/pipeline_component.py
  kpops/components/streams_bootstrap/streams/streams_app.py
  kpops/pipeline_generator/pipeline.py
  kpops/utils/dict_ops.py
  kpops/utils/yaml_loading.py
  poetry.lock
  pyproject.toml
  tests/cli/test_schema_generation.py
  tests/components/test_base_defaults_component.py
  tests/components/test_kafka_sink_connector.py
  tests/components/test_kubernetes_app.py
  tests/components/test_pipeline_component.py
  tests/components/test_producer_app.py
  tests/components/test_streams_app.py
  tests/pipeline/resources/component-type-substitution/infinite_pipeline.yaml
  tests/pipeline/resources/component-type-substitution/pipeline.yaml
  tests/pipeline/resources/kafka-connect-sink-config/config.yaml
  tests/pipeline/resources/kafka-connect-sink-config/pipeline.yaml
  tests/pipeline/resources/pipeline-substitution/pipeline.yaml
  tests/pipeline/resources/pipeline-with-illegal-kubernetes-name/pipeline.yaml
  tests/pipeline/snapshots/snap_test_example.py
  tests/pipeline/snapshots/snap_test_pipeline.py
  tests/pipeline/test_pipeline.py
  tests/utils/test_dict_ops.py
Labels: type/refactor

#244 Fix Helm Version Check
  kpops/component_handlers/helm_wrapper/helm.py
  kpops/component_handlers/helm_wrapper/model.py
  tests/component_handlers/helm_wrapper/test_helm_wrapper.py
Labels: type/bug, area/tests

#249 Add pip cache in KPOps runner action
  actions/kpops-runner/README.md
  actions/kpops-runner/action.yaml
Labels: area/CI

#251 Check types using Pyright
  .github/workflows/ci.yaml
  .pre-commit-config.yaml
  kpops/component_handlers/schema_handler/schema_handler.py
  kpops/component_handlers/topic/handler.py
  kpops/components/base_components/kafka_connector.py
  kpops/components/base_components/models/__init__.py
  kpops/components/base_components/models/from_section.py
  kpops/components/base_components/models/to_section.py
  kpops/components/base_components/pipeline_component.py
  poetry.lock
  pyproject.toml
  tests/cli/resources/module.py
  tests/component_handlers/schema_handler/resources/module.py
  tests/component_handlers/schema_handler/test_schema_handler.py
  tests/component_handlers/topic/test_topic_handler.py
  tests/components/test_base_defaults_component.py
  tests/components/test_kafka_sink_connector.py
  tests/components/test_kafka_source_connector.py
  tests/components/test_streams_app.py
  tests/pipeline/test_components/components.py
Labels: area/CI, area/dependencies

#253 Disable broken Windows CI temporarily
  .github/workflows/ci.yaml
Labels: area/CI

#254 Update release and publish workflows
  .github/changelog-config.json
  .github/workflows/ci.yaml
  .github/workflows/publish-test-pypi.yaml
  .github/workflows/publish.yaml
  .github/workflows/release.yaml
Labels: area/CI

#256 Fix import from external module
  kpops/cli/registry.py
  tests/cli/test_registry.py
  tests/component_handlers/schema_handler/resources/module.py
  tests/component_handlers/schema_handler/test_schema_handler.py
Labels: type/bug

#257 Fix release & publish workflows
  .github/workflows/publish.yaml
  .github/workflows/release.yaml
Labels: area/CI

#258 Fix update docs in release workflow
  .github/workflows/release.yaml
Labels: area/CI

#262 Rename change log message for uncategorized issues
  .github/changelog-config.json
Labels: area/CI

#265 Refactor custom component validation & hide field from kpops output
  kpops/components/base_components/base_defaults_component.py
  kpops/components/base_components/kubernetes_app.py
  kpops/pipeline_generator/pipeline.py
  tests/cli/test_schema_generation.py
Labels: type/bug, type/refactor

#269 Update changelog action to contain miscellaneous PRs
  .github/changelog-config.json
  .github/workflows/release.yaml
Labels: area/CI
