Repository bakdata/kpops, pull requests merged in 2023-10, with the labels that each got.

#354 Make Kafka REST Proxy & Kafka Connect hosts default and improve Schema Registry config
  config.yaml
  docs/docs/developer/auto-generation.md
  docs/docs/resources/pipeline-components/kafka-app.yaml
  docs/docs/resources/pipeline-components/pipeline.yaml
  docs/docs/resources/pipeline-components/producer-app.yaml
  docs/docs/resources/pipeline-components/sections/app-kafka-app.yaml
  docs/docs/resources/pipeline-components/sections/app-producer-app.yaml
  docs/docs/resources/pipeline-components/sections/app-streams-app.yaml
  docs/docs/resources/pipeline-components/streams-app.yaml
  docs/docs/resources/pipeline-defaults/defaults-kafka-app.yaml
  docs/docs/resources/pipeline-defaults/defaults-producer-app.yaml
  docs/docs/resources/pipeline-defaults/defaults-streams-app.yaml
  docs/docs/resources/pipeline-defaults/defaults.yaml
  docs/docs/resources/variables/config_env_vars.env
  docs/docs/resources/variables/config_env_vars.md
  docs/docs/schema/config.json
  docs/docs/user/migration-guide/v2-v3.md
  examples/bakdata/atm-fraud-detection/config.yaml
  examples/bakdata/atm-fraud-detection/defaults.yaml
  hooks/gen_docs/gen_docs_env_vars.py
  kpops/cli/main.py
  kpops/component_handlers/kafka_connect/connect_wrapper.py
  kpops/component_handlers/kafka_connect/kafka_connect_handler.py
  kpops/component_handlers/schema_handler/schema_handler.py
  kpops/component_handlers/topic/handler.py
  kpops/component_handlers/topic/proxy_wrapper.py
  kpops/components/base_components/base_defaults_component.py
  kpops/components/base_components/kafka_connector.py
  kpops/config.py
  kpops/pipeline_generator/pipeline.py
  kpops/utils/gen_schema.py
  tests/cli/test_handlers.py
  tests/cli/test_kpops_config.py
  tests/compiler/test_pipeline_name.py
  tests/component_handlers/kafka_connect/test_connect_wrapper.py
  tests/component_handlers/schema_handler/test_schema_handler.py
  tests/component_handlers/topic/test_proxy_wrapper.py
  tests/components/test_base_defaults_component.py
  tests/components/test_kafka_app.py
  tests/components/test_kafka_connector.py
  tests/components/test_kafka_sink_connector.py
  tests/components/test_kafka_source_connector.py
  tests/components/test_kubernetes_app.py
  tests/components/test_producer_app.py
  tests/components/test_streams_app.py
  tests/pipeline/resources/custom-config/config.yaml
  tests/pipeline/resources/defaults.yaml
  tests/pipeline/resources/kafka-connect-sink-config/config.yaml
  tests/pipeline/resources/no-topics-defaults/defaults.yaml
  tests/pipeline/resources/pipeline-component-should-have-prefix/defaults.yaml
  tests/pipeline/resources/pipeline-with-env-defaults/defaults.yaml
  tests/pipeline/resources/pipeline-with-short-topics/defaults.yaml
  tests/pipeline/test_pipeline.py
Labels: type/refactor, component/config, breaking-change

#378 Migrate deprecated mkdocs-material-extensions
  docs/mkdocs.yml
  poetry.lock
  pyproject.toml
Labels: area/documentation

#377 Fix docs setup page list indentation
  docs/docs/user/examples/atm-fraud-pipeline.md
  docs/docs/user/getting-started/quick-start.md
  docs/docs/user/getting-started/setup.md
  docs/docs/user/getting-started/teardown.md
Labels: type/bug, area/documentation

#371 Exclude resources from docs search
  docs/mkdocs.yml
  poetry.lock
  pyproject.toml
Labels: area/documentation
