Repository bakdata/kpops, pull requests merged in 2024-01, with the labels that each got.

#390 Use hash and trim long Helm release names instead of only trimming
  docs/docs/user/migration-guide/v2-v3.md
  kpops/component_handlers/helm_wrapper/utils.py
  kpops/components/base_components/helm_app.py
  kpops/components/base_components/kafka_app.py
  kpops/components/base_components/kafka_connector.py
  tests/component_handlers/helm_wrapper/test_utils.py
  tests/components/test_kafka_app.py
  tests/components/test_kafka_connector.py
  tests/components/test_kafka_sink_connector.py
  tests/components/test_kafka_source_connector.py
  tests/components/test_kubernetes_app.py
  tests/components/test_producer_app.py
  tests/components/test_streams_app.py
  tests/pipeline/test_template.py
Labels: type/refactor, breaking-change

#397 Refactor Helm `nameOverride`
  docs/docs/schema/pipeline.json
  kpops/component_handlers/kafka_connect/model.py
  kpops/components/base_components/helm_app.py
  kpops/components/base_components/kafka_app.py
  kpops/components/base_components/kafka_connector.py
  kpops/components/base_components/kubernetes_app.py
  kpops/components/streams_bootstrap/producer/model.py
  kpops/components/streams_bootstrap/producer/producer_app.py
  kpops/components/streams_bootstrap/streams/model.py
  kpops/components/streams_bootstrap/streams/streams_app.py
  kpops/pipeline.py
  tests/components/test_helm_app.py
  tests/components/test_kafka_app.py
  tests/components/test_kubernetes_app.py
  tests/components/test_producer_app.py
  tests/components/test_streams_app.py
  tests/pipeline/snapshots/snap_test_example.py
  tests/pipeline/snapshots/snap_test_pipeline.py
Labels: type/refactor, component/pipeline-components

#399 Mark component type as computed Pydantic field
  kpops/components/base_components/base_defaults_component.py
  kpops/pipeline.py
Labels: type/refactor, component/generator

#401 Fix missing component type in pipeline schema
  docs/docs/schema/pipeline.json
  kpops/utils/gen_schema.py
  tests/cli/snapshots/snap_test_schema_generation.py
Labels: type/bug

#380 Refactor generate template for Python API usage
  docs/docs/user/migration-guide/v2-v3.md
  docs/docs/user/references/cli-commands.md
  kpops/__init__.py
  kpops/cli/main.py
  kpops/component_handlers/helm_wrapper/helm.py
  kpops/component_handlers/helm_wrapper/helm_diff.py
  kpops/component_handlers/helm_wrapper/model.py
  kpops/component_handlers/kubernetes/__init__.py
  kpops/component_handlers/kubernetes/model.py
  kpops/components/base_components/helm_app.py
  kpops/components/base_components/kafka_connector.py
  kpops/components/base_components/models/resource.py
  kpops/components/base_components/pipeline_component.py
  kpops/utils/dict_differ.py
  kpops/utils/yaml.py
  tests/component_handlers/helm_wrapper/test_dry_run_handler.py
  tests/component_handlers/helm_wrapper/test_helm_diff.py
  tests/component_handlers/helm_wrapper/test_helm_wrapper.py
  tests/component_handlers/kubernetes/__init__.py
  tests/component_handlers/kubernetes/model.py
  tests/pipeline/snapshots/snap_test_generate.py
  tests/pipeline/snapshots/snap_test_manifest.py
  tests/pipeline/test_generate.py
  tests/pipeline/test_manifest.py
Labels: type/refactor, component/handlers, component/pipeline-components, breaking-change

#402 Generate defaults schema
  docs/docs/resources/editor_integration/settings.json
  docs/docs/schema/defaults.json
  docs/docs/user/references/cli-commands.md
  docs/docs/user/references/editor-integration.md
  hooks/gen_schema.py
  kpops/cli/main.py
  kpops/utils/gen_schema.py
  tests/cli/test_schema_generation.py
Labels: type/enhancement, component/cli

#409 Update docs for substitution variable usage in v3
  docs/docs/resources/pipeline-components/kafka-app.yaml
  docs/docs/resources/pipeline-components/pipeline.yaml
  docs/docs/resources/pipeline-components/producer-app.yaml
  docs/docs/resources/pipeline-components/sections/app-kafka-app.yaml
  docs/docs/resources/pipeline-components/sections/app-producer-app.yaml
  docs/docs/resources/pipeline-components/sections/app-streams-app.yaml
  docs/docs/resources/pipeline-components/streams-app.yaml
  docs/docs/resources/pipeline-defaults/defaults-kafka-app.yaml
  docs/docs/resources/pipeline-defaults/defaults-producer-app.yaml
  docs/docs/resources/pipeline-defaults/defaults-streams-app.yaml
  docs/docs/resources/pipeline-defaults/defaults.yaml
Labels: area/documentation

#408 Namespace substitution vars
  docs/docs/resources/pipeline-components/helm-app.yaml
  docs/docs/resources/pipeline-components/kafka-app.yaml
  docs/docs/resources/pipeline-components/kafka-connector.yaml
  docs/docs/resources/pipeline-components/kafka-sink-connector.yaml
  docs/docs/resources/pipeline-components/kafka-source-connector.yaml
  docs/docs/resources/pipeline-components/kubernetes-app.yaml
  docs/docs/resources/pipeline-components/pipeline.yaml
  docs/docs/resources/pipeline-components/producer-app.yaml
  docs/docs/resources/pipeline-components/sections/app-kafka-app.yaml
  docs/docs/resources/pipeline-components/sections/app-producer-app.yaml
  docs/docs/resources/pipeline-components/sections/app-streams-app.yaml
  docs/docs/resources/pipeline-components/sections/from_.yaml
  docs/docs/resources/pipeline-components/sections/prefix.yaml
  docs/docs/resources/pipeline-components/sections/to.yaml
  docs/docs/resources/pipeline-components/streams-app.yaml
  docs/docs/resources/pipeline-config/config.yaml
  docs/docs/resources/pipeline-defaults/defaults-kafka-app.yaml
  docs/docs/resources/pipeline-defaults/defaults-kafka-connector.yaml
  docs/docs/resources/pipeline-defaults/defaults-kubernetes-app.yaml
  docs/docs/resources/pipeline-defaults/defaults-producer-app.yaml
  docs/docs/resources/pipeline-defaults/defaults-streams-app.yaml
  docs/docs/resources/pipeline-defaults/defaults.yaml
  docs/docs/resources/variables/config_env_vars.env
  docs/docs/resources/variables/config_env_vars.md
  docs/docs/schema/config.json
  docs/docs/schema/defaults.json
  docs/docs/schema/pipeline.json
  docs/docs/user/core-concepts/variables/substitution.md
  docs/docs/user/migration-guide/v2-v3.md
  examples/bakdata/atm-fraud-detection/config.yaml
  examples/bakdata/atm-fraud-detection/defaults.yaml
  examples/bakdata/atm-fraud-detection/pipeline.yaml
  kpops/components/base_components/pipeline_component.py
  kpops/config.py
  kpops/pipeline.py
  tests/cli/snapshots/snap_test_schema_generation.py
  tests/cli/test_kpops_config.py
  tests/compiler/test_pipeline_name.py
  tests/components/test_helm_app.py
  tests/components/test_kafka_app.py
  tests/components/test_kafka_connector.py
  tests/components/test_kubernetes_app.py
  tests/components/test_producer_app.py
  tests/components/test_streams_app.py
  tests/pipeline/resources/defaults.yaml
  tests/pipeline/resources/no-topics-defaults/defaults.yaml
  tests/pipeline/resources/pipeline-component-should-have-prefix/defaults.yaml
  tests/pipeline/resources/pipeline-with-env-defaults/defaults.yaml
  tests/pipeline/resources/pipeline-with-short-topics/defaults.yaml
  tests/pipeline/resources/read-from-component/pipeline.yaml
  tests/pipeline/resources/temp-trim-release-name/defaults.yaml
Labels: breaking-change

#406 Support multiple inheritance for doc generation
  docs/docs/resources/pipeline-components/dependencies/kpops_structure.yaml
  hooks/gen_docs/gen_docs_components.py
  hooks/gen_docs/gen_docs_env_vars.py
  kpops/components/base_components/pipeline_component.py
  kpops/utils/pydantic.py
Labels: area/documentation, type/refactor, area/CI

#398 Refactor streams-bootstrap cleanup jobs as individual HelmApp
  docs/docs/resources/architecture/components-hierarchy.md
  docs/docs/resources/pipeline-components/dependencies/defaults_pipeline_component_dependencies.yaml
  docs/docs/resources/pipeline-components/dependencies/kpops_structure.yaml
  docs/docs/resources/pipeline-components/dependencies/pipeline_component_dependencies.yaml
  docs/docs/resources/pipeline-components/kafka-app.yaml
  docs/docs/resources/pipeline-components/pipeline.yaml
  docs/docs/resources/pipeline-defaults/defaults-kafka-app.yaml
  docs/docs/resources/pipeline-defaults/defaults.yaml
  docs/docs/schema/defaults.json
  docs/docs/schema/pipeline.json
  docs/docs/user/core-concepts/components/producer-app.md
  docs/docs/user/core-concepts/components/streams-app.md
  docs/docs/user/core-concepts/components/streams-bootstrap.md
  docs/docs/user/migration-guide/v2-v3.md
  docs/mkdocs.yml
  kpops/components/__init__.py
  kpops/components/base_components/kafka_app.py
  kpops/components/streams_bootstrap/__init__.py
  kpops/components/streams_bootstrap/producer/producer_app.py
  kpops/components/streams_bootstrap/streams/model.py
  kpops/components/streams_bootstrap/streams/streams_app.py
  tests/cli/test_registry.py
  tests/components/test_producer_app.py
  tests/components/test_streams_app.py
  tests/components/test_streams_bootstrap.py
  tests/pipeline/test_components/components.py
  tests/pipeline/test_components_without_schema_handler/components.py
Labels: type/refactor, component/pipeline-components, breaking-change

#416 Update docs for v3
  docs/docs/resources/pipeline-config/config.yaml
  docs/docs/user/core-concepts/variables/substitution.md
Labels: area/documentation

#400 Refactor Kafka Connector resetter as individual HelmApp
  docs/docs/resources/pipeline-components/dependencies/defaults_pipeline_component_dependencies.yaml
  docs/docs/resources/pipeline-components/dependencies/kpops_structure.yaml
  docs/docs/resources/pipeline-components/dependencies/pipeline_component_dependencies.yaml
  docs/docs/resources/pipeline-components/kafka-connector.yaml
  docs/docs/resources/pipeline-components/kafka-sink-connector.yaml
  docs/docs/resources/pipeline-components/kafka-source-connector.yaml
  docs/docs/resources/pipeline-components/pipeline.yaml
  docs/docs/resources/pipeline-defaults/defaults-kafka-connector.yaml
  docs/docs/resources/pipeline-defaults/defaults.yaml
  docs/docs/schema/defaults.json
  docs/docs/schema/pipeline.json
  docs/docs/user/migration-guide/v2-v3.md
  examples/bakdata/atm-fraud-detection/defaults.yaml
  kpops/components/base_components/base_defaults_component.py
  kpops/components/base_components/helm_app.py
  kpops/components/base_components/kafka_connector.py
  kpops/components/base_components/kubernetes_app.py
  tests/components/test_kafka_connector.py
  tests/components/test_kafka_sink_connector.py
  tests/components/test_kafka_source_connector.py
  tests/pipeline/resources/defaults.yaml
  tests/pipeline/resources/kafka-connect-sink/pipeline.yaml
  tests/pipeline/snapshots/snap_test_example.py
  tests/pipeline/snapshots/snap_test_generate.py
  tests/pipeline/test_components/components.py
  tests/pipeline/test_components_without_schema_handler/components.py
Labels: type/refactor, component/pipeline-components, breaking-change

#417 Update tests resources
  tests/pipeline/resources/dotenv/config.yaml
  tests/pipeline/resources/env-specific-config-only/config_production.yaml
  tests/pipeline/resources/multi-config/config.yaml
Labels: area/documentation

#415 Fix enrichment of nested Pydantic BaseModel
  kpops/component_handlers/kubernetes/model.py
  kpops/components/base_components/base_defaults_component.py
  kpops/pipeline.py
  kpops/utils/dict_ops.py
  kpops/utils/types.py
  tests/components/resources/defaults.yaml
  tests/components/test_base_defaults_component.py
  tests/pipeline/snapshots/snap_test_generate.py
  tests/pipeline/test_components/components.py
  tests/utils/test_dict_ops.py
Labels: type/bug

#419 Summarize all breaking changes in diffs at the top of the migration guide
  docs/docs/user/migration-guide/v2-v3.md
Labels: area/documentation

#418 Fix wrong Helm release name character limit
  docs/docs/user/migration-guide/v2-v3.md
  kpops/component_handlers/helm_wrapper/utils.py
  tests/component_handlers/helm_wrapper/test_utils.py
  tests/components/test_kafka_connector.py
Labels: type/bug, breaking-change

#421 Update release workflow template to support custom changelog file path
  .github/workflows/release.yaml
Labels: type/bug, area/CI

#422 Update pydantic dependency
  poetry.lock
  pyproject.toml
Labels: area/dependencies

#423 Update docs of word-count example for v3 & new folder structure
  docs/docs/resources/examples/defaults.md
  docs/docs/resources/examples/pipeline.md
  docs/docs/user/getting-started/quick-start.md
  docs/docs/user/what-is-kpops.md
Labels: area/documentation

#427 Fix broken doc link
  docs/docs/resources/architecture/components-hierarchy.md
  docs/docs/resources/examples/pipeline.md
Labels: type/bug, area/documentation

#428 Add warning log if SR handler is disabled but URL is set
  kpops/component_handlers/schema_handler/schema_handler.py
  tests/component_handlers/schema_handler/test_schema_handler.py
Labels: type/bug, component/handlers

#431 Add step for submodule initialization on the docs
  docs/docs/developer/contributing.md
Labels: area/documentation

#432 Add message if examples git submodule is not initialized
  tests/pipeline/test_example.py
Labels: area/tests

#433 Update type annotation for deserialized pipeline
  tests/pipeline/test_example.py
  tests/pipeline/test_generate.py
Labels: area/tests

#434 Fix Helm diff output
  kpops/component_handlers/helm_wrapper/helm_diff.py
  tests/component_handlers/helm_wrapper/test_dry_run_handler.py
  tests/component_handlers/helm_wrapper/test_helm_diff.py
Labels: type/bug, area/tests, component/handlers

#435 Simplify loading of defaults
  docs/docs/resources/pipeline-components/dependencies/kpops_structure.yaml
  kpops/components/base_components/base_defaults_component.py
  kpops/components/base_components/pipeline_component.py
  tests/components/test_base_defaults_component.py
Labels: type/refactor, component/pipeline-components

#430 Update poetry publish workflow version to latest
  .github/workflows/ci.yaml
  .github/workflows/publish.yaml
  .github/workflows/release.yaml
Labels: type/bug, area/CI

#312 Add support for pipeline steps parallelization
  docs/docs/user/references/cli-commands.md
  kpops/cli/main.py
  kpops/component_handlers/helm_wrapper/helm.py
  kpops/component_handlers/kafka_connect/connect_wrapper.py
  kpops/component_handlers/kafka_connect/kafka_connect_handler.py
  kpops/component_handlers/kafka_connect/timeout.py
  kpops/component_handlers/schema_handler/schema_handler.py
  kpops/component_handlers/topic/handler.py
  kpops/component_handlers/topic/proxy_wrapper.py
  kpops/components/base_components/helm_app.py
  kpops/components/base_components/kafka_app.py
  kpops/components/base_components/kafka_connector.py
  kpops/components/base_components/pipeline_component.py
  kpops/components/streams_bootstrap/producer/producer_app.py
  kpops/components/streams_bootstrap/streams/streams_app.py
  kpops/pipeline.py
  poetry.lock
  pyproject.toml
  tests/cli/test_pipeline_steps.py
  tests/component_handlers/helm_wrapper/test_helm_wrapper.py
  tests/component_handlers/kafka_connect/test_connect_handler.py
  tests/component_handlers/kafka_connect/test_connect_wrapper.py
  tests/component_handlers/schema_handler/test_schema_handler.py
  tests/component_handlers/topic/test_proxy_wrapper.py
  tests/component_handlers/topic/test_topic_handler.py
  tests/components/test_helm_app.py
  tests/components/test_kafka_connector.py
  tests/components/test_kafka_sink_connector.py
  tests/components/test_kafka_source_connector.py
  tests/components/test_kubernetes_app.py
  tests/components/test_producer_app.py
  tests/components/test_streams_app.py
  tests/components/test_streams_bootstrap.py
  tests/pipeline/resources/parallel-pipeline/config.yaml
  tests/pipeline/resources/parallel-pipeline/defaults.yaml
  tests/pipeline/resources/parallel-pipeline/pipeline.yaml
  tests/pipeline/resources/pipeline-with-loop/defaults.yaml
  tests/pipeline/resources/pipeline-with-loop/pipeline.yaml
  tests/pipeline/resources/pipeline-with-short-topics/defaults.yaml
  tests/pipeline/resources/pipelines-with-graphs/same-topic-and-component-name/config.yaml
  tests/pipeline/resources/pipelines-with-graphs/same-topic-and-component-name/defaults.yaml
  tests/pipeline/resources/pipelines-with-graphs/same-topic-and-component-name/pipeline.yaml
  tests/pipeline/resources/pipelines-with-graphs/simple-pipeline/config.yaml
  tests/pipeline/resources/pipelines-with-graphs/simple-pipeline/defaults.yaml
  tests/pipeline/resources/pipelines-with-graphs/simple-pipeline/pipeline.yaml
  tests/pipeline/test_generate.py
Labels: type/enhancement, component/generator, component/handlers, component/cli

#439 Add parallel flag support to kpops runner
  CONTRIBUTING.md
  action.yaml
  docs/docs/user/references/ci-integration/github-actions.md
Labels: area/CI
