Repository bakdata/kpops, pull requests merged in 2024-07, with the labels that each got.

#503 Generate developer docs for Python API
  docs/docs/developer/api.md
  docs/mkdocs.yml
  kpops/api/__init__.py
  poetry.lock
  pyproject.toml
  tests/api/test_handlers.py
Labels: area/documentation

#499 Add image tag field to streams-bootstrap app values
  docs/docs/schema/defaults.json
  docs/docs/schema/pipeline.json
  kpops/components/streams_bootstrap/__init__.py
  kpops/components/streams_bootstrap/producer/model.py
  kpops/components/streams_bootstrap/streams/model.py
  tests/components/test_kafka_sink_connector.py
  tests/components/test_streams_bootstrap.py
  tests/pipeline/resources/resetter_values/defaults.yaml
  tests/pipeline/snapshots/test_generate/test_default_config/pipeline.yaml
  tests/pipeline/snapshots/test_generate/test_inflate_pipeline/pipeline.yaml
  tests/pipeline/snapshots/test_generate/test_kafka_connect_sink_weave_from_topics/pipeline.yaml
  tests/pipeline/snapshots/test_generate/test_load_pipeline/pipeline.yaml
  tests/pipeline/snapshots/test_generate/test_load_pipeline_with_folder_path/pipeline.yaml
  tests/pipeline/snapshots/test_generate/test_load_pipeline_with_multiple_pipeline_paths/pipeline.yaml
  tests/pipeline/snapshots/test_generate/test_model_serialization/pipeline.yaml
  tests/pipeline/snapshots/test_generate/test_no_input_topic/pipeline.yaml
  tests/pipeline/snapshots/test_generate/test_no_user_defined_components/pipeline.yaml
  tests/pipeline/snapshots/test_generate/test_pipelines_with_envs/pipeline.yaml
  tests/pipeline/snapshots/test_generate/test_read_from_component/pipeline.yaml
  tests/pipeline/snapshots/test_generate/test_substitute_in_component/pipeline.yaml
  tests/pipeline/snapshots/test_generate/test_with_custom_config_with_absolute_defaults_path/pipeline.yaml
  tests/pipeline/snapshots/test_generate/test_with_custom_config_with_relative_defaults_path/pipeline.yaml
  tests/pipeline/snapshots/test_generate/test_with_env_defaults/pipeline.yaml
  tests/pipeline/test_generate.py
Labels: type/enhancement, component/pipeline-components

#500 Automatic loading of namespaced custom components
  config.yaml
  docs/docs/resources/pipeline-config/config.yaml
  docs/docs/resources/variables/config_env_vars.env
  docs/docs/resources/variables/config_env_vars.md
  docs/docs/schema/config.json
  docs/docs/user/migration-guide/v6-v7.md
  docs/docs/user/references/cli-commands.md
  docs/mkdocs.yml
  hooks/gen_docs/gen_docs_components.py
  kpops/__init__.py
  kpops/api/__init__.py
  kpops/api/file_type.py
  kpops/api/logs.py
  kpops/api/options.py
  kpops/api/registry.py
  kpops/cli/main.py
  kpops/cli/utils.py
  kpops/component_handlers/schema_handler/schema_handler.py
  kpops/components/__init__.py
  kpops/components/base_components/__init__.py
  kpops/components/base_components/kafka_app.py
  kpops/components/common/__init__.py
  kpops/components/common/streams_bootstrap.py
  kpops/components/streams_bootstrap/__init__.py
  kpops/components/streams_bootstrap/producer/model.py
  kpops/components/streams_bootstrap/producer/producer_app.py
  kpops/components/streams_bootstrap/streams/model.py
  kpops/components/streams_bootstrap/streams/streams_app.py
  kpops/config/__init__.py
  kpops/const/__init__.py
  kpops/pipeline/__init__.py
  kpops/utils/gen_schema.py
  pyproject.toml
  tests/api/test_handlers.py
  tests/api/test_registry.py
  tests/cli/resources/config.yaml
  tests/cli/resources/empty_module/config.yaml
  tests/cli/resources/no_module/config.yaml
  tests/cli/snapshots/test_init/test_init_project/config_include_opt.yaml
  tests/cli/test_init.py
  tests/cli/test_schema_generation.py
  tests/component_handlers/schema_handler/test_schema_handler.py
  tests/components/test_base_defaults_component.py
  tests/components/test_kafka_sink_connector.py
  tests/components/test_producer_app.py
  tests/components/test_streams_app.py
  tests/components/test_streams_bootstrap.py
  tests/conftest.py
  tests/pipeline/test_components/components.py
  tests/pipeline/test_components_without_schema_handler/components.py
  tests/pipeline/test_example.py
  tests/pipeline/test_generate.py
  tests/pipeline/test_manifest.py
  tests/pipeline/test_pipeline.py
Labels: component/pipeline-components, component/config, breaking-change

#507 Improve dataclass instance check
  kpops/components/base_components/base_defaults_component.py
  kpops/utils/dataclasses.py
Labels: type/refactor

#501 Call destroy from inside of reset or clean
  docs/docs/user/migration-guide/v6-v7.md
  kpops/api/__init__.py
  kpops/components/base_components/kafka_connector.py
  kpops/components/base_components/pipeline_component.py
  kpops/components/streams_bootstrap/producer/producer_app.py
  kpops/components/streams_bootstrap/streams/streams_app.py
  tests/components/test_helm_app.py
  tests/components/test_kafka_sink_connector.py
  tests/components/test_kafka_source_connector.py
  tests/components/test_producer_app.py
  tests/components/test_streams_app.py
  tests/components/test_streams_bootstrap.py
  tests/pipeline/test_clean.py
  tests/pipeline/test_reset.py
Labels: type/refactor, breaking-change

#498 clean/reset streams-bootstrap components with cluster values
  kpops/component_handlers/helm_wrapper/helm.py
  kpops/components/streams_bootstrap/producer/producer_app.py
  kpops/components/streams_bootstrap/streams/streams_app.py
  tests/components/test_producer_app.py
  tests/components/test_streams_app.py
  tests/pipeline/test_clean.py
  tests/pipeline/test_reset.py
Labels: type/enhancement

#515 Improve incomplete type hints
  .github/ruff-matcher.json
  .github/workflows/ci.yaml
  kpops/component_handlers/__init__.py
  kpops/component_handlers/helm_wrapper/helm_diff.py
  kpops/component_handlers/kafka_connect/connect_wrapper.py
  kpops/component_handlers/kafka_connect/model.py
  kpops/component_handlers/topic/handler.py
  kpops/component_handlers/topic/proxy_wrapper.py
  kpops/component_handlers/topic/utils.py
  kpops/components/base_components/base_defaults_component.py
  kpops/components/base_components/helm_app.py
  kpops/components/base_components/kafka_app.py
  kpops/components/common/topic.py
  kpops/components/streams_bootstrap/streams/model.py
  kpops/pipeline/__init__.py
  kpops/utils/__init__.py
  kpops/utils/dict_differ.py
  kpops/utils/yaml.py
  poetry.lock
  pyproject.toml
  tests/utils/test_diff.py
Labels: type/refactor
