Repository bakdata/kpops, pull requests merged in 2024-02, with the labels that each got.

#443 Improve Sphinx docs highlighting using RST markup
  docs/docs/resources/variables/config_env_vars.env
  docs/docs/resources/variables/config_env_vars.md
  docs/docs/schema/config.json
  docs/docs/schema/defaults.json
  docs/docs/schema/pipeline.json
  kpops/cli/exception.py
  kpops/component_handlers/helm_wrapper/helm.py
  kpops/component_handlers/helm_wrapper/model.py
  kpops/component_handlers/helm_wrapper/utils.py
  kpops/component_handlers/kafka_connect/connect_wrapper.py
  kpops/component_handlers/kafka_connect/kafka_connect_handler.py
  kpops/component_handlers/topic/proxy_wrapper.py
  kpops/components/base_components/base_defaults_component.py
  kpops/components/base_components/kafka_connector.py
  kpops/components/base_components/models/from_section.py
  kpops/components/base_components/models/to_section.py
  kpops/components/base_components/pipeline_component.py
  kpops/pipeline.py
  kpops/utils/pydantic.py
  kpops/utils/yaml.py
  tests/cli/snapshots/snap_test_schema_generation.py
Labels: area/documentation

#444 Refactor enrichment using Pydantic model validator
  kpops/components/base_components/base_defaults_component.py
  kpops/components/base_components/kubernetes_app.py
  kpops/utils/gen_schema.py
  poetry.lock
Labels: type/refactor, component/pipeline-components, area/dependencies

#446 Simplify execution graph logic
  kpops/pipeline.py
  tests/pipeline/test_generate.py
Labels: type/refactor

#450 Fix order of pipeline steps for clean/reset
  kpops/cli/main.py
  tests/pipeline/resources/simple-pipeline/pipeline.yaml
  tests/pipeline/test_clean.py
  tests/pipeline/test_deploy.py
  tests/pipeline/test_destroy.py
  tests/pipeline/test_reset.py
Labels: type/bug, area/tests, component/cli

#449 Fix substitution
  docs/docs/schema/defaults.json
  docs/docs/schema/pipeline.json
  kpops/components/base_components/base_defaults_component.py
  kpops/components/base_components/kafka_app.py
  kpops/components/base_components/kafka_connector.py
  kpops/components/streams_bootstrap/producer/producer_app.py
  kpops/components/streams_bootstrap/streams/streams_app.py
  kpops/pipeline.py
  kpops/utils/gen_schema.py
  tests/components/test_helm_app.py
  tests/components/test_kafka_connector.py
  tests/components/test_producer_app.py
  tests/components/test_streams_app.py
  tests/components/test_streams_bootstrap.py
  tests/conftest.py
  tests/pipeline/resources/resetter_values/defaults.yaml
  tests/pipeline/resources/resetter_values/pipeline.yaml
  tests/pipeline/resources/resetter_values/pipeline_connector_only.yaml
  tests/pipeline/snapshots/snap_test_example.py
  tests/pipeline/snapshots/snap_test_generate.py
  tests/pipeline/test_components/__init__.py
  tests/pipeline/test_components/components.py
  tests/pipeline/test_generate.py
Labels: type/bug, component/generator

#452 Fix cleaner inheritance, parent model should be aliased during instantiation
  kpops/components/base_components/kafka_connector.py
  kpops/components/streams_bootstrap/producer/producer_app.py
  kpops/components/streams_bootstrap/streams/streams_app.py
  tests/components/test_kafka_sink_connector.py
  tests/components/test_producer_app.py
  tests/components/test_streams_app.py
Labels: type/bug, component/pipeline-components

#437 Log picked up files in verbose mode
  kpops/cli/registry.py
  kpops/components/base_components/base_defaults_component.py
  kpops/pipeline.py
  kpops/utils/yaml.py
Labels: type/enhancement

#456 Trim and hash Helm name override to 63 characters
  docs/docs/schema/defaults.json
  docs/docs/schema/pipeline.json
  kpops/component_handlers/helm_wrapper/utils.py
  kpops/component_handlers/kubernetes/model.py
  kpops/component_handlers/kubernetes/utils.py
  kpops/components/base_components/cleaner.py
  kpops/components/base_components/helm_app.py
  kpops/components/base_components/kafka_app.py
  kpops/components/base_components/kafka_connector.py
  tests/components/test_helm_app.py
  tests/components/test_kafka_connector.py
  tests/components/test_kafka_sink_connector.py
  tests/components/test_kafka_source_connector.py
  tests/components/test_producer_app.py
  tests/components/test_streams_app.py
  tests/pipeline/snapshots/snap_test_example.py
  tests/pipeline/snapshots/snap_test_generate.py
Labels: type/bug, area/tests, component/pipeline-components

#447 Refactor Kafka topics
  docs/docs/schema/defaults.json
  docs/docs/schema/pipeline.json
  kpops/cli/main.py
  kpops/component_handlers/kafka_connect/model.py
  kpops/component_handlers/topic/handler.py
  kpops/components/__init__.py
  kpops/components/base_components/__init__.py
  kpops/components/base_components/base_defaults_component.py
  kpops/components/base_components/kafka_app.py
  kpops/components/base_components/kafka_connector.py
  kpops/components/base_components/models/to_section.py
  kpops/components/base_components/models/topic.py
  kpops/components/base_components/pipeline_component.py
  kpops/components/streams_bootstrap/producer/model.py
  kpops/components/streams_bootstrap/producer/producer_app.py
  kpops/components/streams_bootstrap/streams/model.py
  kpops/components/streams_bootstrap/streams/streams_app.py
  kpops/pipeline.py
  tests/cli/test_schema_generation.py
  tests/component_handlers/kafka_connect/test_connect_handler.py
  tests/component_handlers/kafka_connect/test_connect_wrapper.py
  tests/component_handlers/schema_handler/test_schema_handler.py
  tests/component_handlers/topic/test_topic_handler.py
  tests/components/test_kafka_connector.py
  tests/components/test_kafka_sink_connector.py
  tests/components/test_kafka_source_connector.py
  tests/components/test_producer_app.py
  tests/components/test_streams_app.py
  tests/components/test_topic.py
  tests/pipeline/snapshots/snap_test_example.py
  tests/pipeline/snapshots/snap_test_generate.py
  tests/pipeline/test_components/components.py
  tests/pipeline/test_components_without_schema_handler/components.py
  tests/pipeline/test_generate.py
  tests/utils/test_pydantic.py
Labels: type/refactor, component/handlers, component/pipeline-components

#459 Fix docs CI to include the latest changes to a tagged version in the changelog
  .github/actions/update-docs/action.yml
  .github/workflows/release.yaml
  .github/workflows/update-gh-pages.yaml
Labels: type/bug, area/documentation, area/CI

#460 Refactor PipelineGenerator to use component ids
  kpops/pipeline.py
Labels: type/refactor, component/generator

#461 Fix tempfile creation
  kpops/component_handlers/helm_wrapper/helm.py
Labels: type/bug

#462 Fix symbolic link to CONTRIBUTING.md and parallel option in action.yaml
  CONTRIBUTING.md
  action.yaml
Labels: type/bug, area/CI

#466 Set supported Python cutoff to 3.11
  poetry.lock
  pyproject.toml
Labels: type/bug, area/dependencies

#467 Add support for Python 3.12
  .github/workflows/ci.yaml
  kpops/cli/registry.py
  poetry.lock
  pyproject.toml
  tests/cli/snapshots/__init__.py
  tests/cli/snapshots/test_schema_generation/test_gen_pipeline_schema_only_custom_module/schema.json
  tests/cli/test_schema_generation.py
  tests/pipeline/snapshots/__init__.py
  tests/pipeline/snapshots/snap_test_example.py
  tests/pipeline/snapshots/snap_test_generate.py
  tests/pipeline/snapshots/snap_test_manifest.py
  tests/pipeline/snapshots/snap_test_pipeline.py
  tests/pipeline/snapshots/test_example/test_generate/atm-fraud/pipeline.yaml
  tests/pipeline/snapshots/test_example/test_generate/word-count/pipeline.yaml
  tests/pipeline/snapshots/test_generate/test_default_config/pipeline.yaml
  tests/pipeline/snapshots/test_generate/test_inflate_pipeline/pipeline.yaml
  tests/pipeline/snapshots/test_generate/test_kafka_connect_sink_weave_from_topics/pipeline.yaml
  tests/pipeline/snapshots/test_generate/test_load_pipeline/pipeline.yaml
  tests/pipeline/snapshots/test_generate/test_model_serialization/pipeline.yaml
  tests/pipeline/snapshots/test_generate/test_no_input_topic/pipeline.yaml
  tests/pipeline/snapshots/test_generate/test_no_user_defined_components/pipeline.yaml
  tests/pipeline/snapshots/test_generate/test_pipelines_with_envs/pipeline.yaml
  tests/pipeline/snapshots/test_generate/test_prefix_pipeline_component/pipeline.yaml
  tests/pipeline/snapshots/test_generate/test_read_from_component/pipeline.yaml
  tests/pipeline/snapshots/test_generate/test_substitute_in_component/pipeline.yaml
  tests/pipeline/snapshots/test_generate/test_with_custom_config_with_absolute_defaults_path/pipeline.yaml
  tests/pipeline/snapshots/test_generate/test_with_custom_config_with_relative_defaults_path/pipeline.yaml
  tests/pipeline/snapshots/test_generate/test_with_env_defaults/pipeline.yaml
  tests/pipeline/snapshots/test_manifest/test_python_api/resources
  tests/pipeline/test_example.py
  tests/pipeline/test_generate.py
  tests/pipeline/test_manifest.py
Labels: area/CI, area/dependencies

#468 Update Pyright
  .pre-commit-config.yaml
  hooks/gen_docs/gen_docs_env_vars.py
  kpops/cli/main.py
  kpops/component_handlers/kafka_connect/kafka_connect_handler.py
  kpops/component_handlers/kubernetes/model.py
  kpops/component_handlers/schema_handler/schema_handler.py
  kpops/components/base_components/base_defaults_component.py
  kpops/config.py
  kpops/utils/gen_schema.py
  poetry.lock
  pyproject.toml
  tests/cli/test_kpops_config.py
  tests/component_handlers/kafka_connect/test_connect_handler.py
  tests/component_handlers/kafka_connect/test_connect_wrapper.py
  tests/component_handlers/schema_handler/test_schema_handler.py
  tests/component_handlers/topic/test_proxy_wrapper.py
  tests/components/test_topic.py
  tests/conftest.py
Labels: area/CI, area/dependencies
