Repository bakdata/kpops, pull requests merged in 2024-05, with the labels that each got.

#485 Allow custom timeout for external services
  README.md
  docs/docs/resources/variables/config_env_vars.env
  docs/docs/resources/variables/config_env_vars.md
  docs/docs/schema/config.json
  docs/docs/user/migration-guide/v4-v5.md
  docs/mkdocs.yml
  kpops/component_handlers/kafka_connect/connect_wrapper.py
  kpops/component_handlers/kafka_connect/kafka_connect_handler.py
  kpops/component_handlers/schema_handler/schema_handler.py
  kpops/component_handlers/topic/proxy_wrapper.py
  kpops/config.py
  tests/cli/snapshots/test_init/test_init_project/config_include_opt.yaml
  tests/cli/test_kpops_config.py
  tests/component_handlers/kafka_connect/test_connect_handler.py
Labels: component/config, breaking-change

#491 Add YAML separator (---) to stdout
  kpops/utils/yaml.py
  tests/pipeline/snapshots/test_manifest/test_manifest_command/manifest.yaml
  tests/pipeline/test_manifest.py
Labels: type/bug

#489 Separate KPOps API from the CLI
  docs/docs/user/references/cli-commands.md
  hooks/gen_docs/gen_docs_components.py
  kpops/__init__.py
  kpops/api/__init__.py
  kpops/api/exception.py
  kpops/api/logs.py
  kpops/api/options.py
  kpops/api/registry.py
  kpops/cli/exception.py
  kpops/cli/main.py
  kpops/cli/options.py
  kpops/component_handlers/schema_handler/schema_handler.py
  kpops/components/streams_bootstrap/streams/model.py
  kpops/config.py
  kpops/pipeline.py
  kpops/utils/gen_schema.py
  poetry.lock
  pyproject.toml
  tests/api/__init__.py
  tests/api/test_handlers.py
  tests/api/test_registry.py
  tests/cli/test_schema_generation.py
  tests/components/test_streams_app.py
  tests/pipeline/test_generate.py
  tests/pipeline/test_manifest.py
  tests/pipeline/test_pipeline.py
  tests/test_kpops_config.py
Labels: type/refactor, breaking-change

#494 Revert "Add computed field for Helm release name and name override (#…
  docs/docs/resources/variables/variable_substitution.yaml
  kpops/components/base_components/helm_app.py
  tests/pipeline/resources/component-type-substitution/pipeline.yaml
  tests/pipeline/snapshots/test_example/test_generate/atm-fraud/pipeline.yaml
  tests/pipeline/snapshots/test_example/test_generate/word-count/pipeline.yaml
  tests/pipeline/snapshots/test_generate/test_default_config/pipeline.yaml
  tests/pipeline/snapshots/test_generate/test_inflate_pipeline/pipeline.yaml
  tests/pipeline/snapshots/test_generate/test_kafka_connect_sink_weave_from_topics/pipeline.yaml
  tests/pipeline/snapshots/test_generate/test_load_pipeline/pipeline.yaml
  tests/pipeline/snapshots/test_generate/test_load_pipeline_with_folder_path/pipeline.yaml
  tests/pipeline/snapshots/test_generate/test_load_pipeline_with_multiple_pipeline_paths/pipeline.yaml
  tests/pipeline/snapshots/test_generate/test_model_serialization/pipeline.yaml
  tests/pipeline/snapshots/test_generate/test_no_input_topic/pipeline.yaml
  tests/pipeline/snapshots/test_generate/test_no_user_defined_components/pipeline.yaml
  tests/pipeline/snapshots/test_generate/test_pipelines_with_envs/pipeline.yaml
  tests/pipeline/snapshots/test_generate/test_prefix_pipeline_component/pipeline.yaml
  tests/pipeline/snapshots/test_generate/test_read_from_component/pipeline.yaml
  tests/pipeline/snapshots/test_generate/test_substitute_in_component/pipeline.yaml
  tests/pipeline/snapshots/test_generate/test_with_custom_config_with_absolute_defaults_path/pipeline.yaml
  tests/pipeline/snapshots/test_generate/test_with_custom_config_with_relative_defaults_path/pipeline.yaml
  tests/pipeline/snapshots/test_generate/test_with_env_defaults/pipeline.yaml
Labels: breaking-change

#495 Remove default filename prefix from KPOps config
  docs/docs/resources/pipeline-config/config.yaml
  docs/docs/resources/variables/config_env_vars.env
  docs/docs/resources/variables/config_env_vars.md
  docs/docs/schema/config.json
  docs/docs/user/core-concepts/defaults.md
  kpops/components/base_components/base_defaults_component.py
  kpops/config.py
  tests/cli/snapshots/test_init/test_init_project/config_include_opt.yaml
  tests/test_kpops_config.py
Labels: component/config, breaking-change
