Repository bakdata/kpops, pull requests merged in 2024-03, with the labels that each got.

#465 Document precedence between env vars and config.yaml
  docs/docs/resources/variables/cli_env_vars.env
  docs/docs/resources/variables/cli_env_vars.md
  docs/docs/resources/variables/config_env_vars.env
  docs/docs/resources/variables/config_env_vars.md
  hooks/gen_docs/gen_docs_env_vars.py
  kpops/config.py
Labels: area/documentation

#471 Update httpx
  poetry.lock
  pyproject.toml
Labels: area/dependencies

#472 Fix import errors
  hooks/gen_docs/gen_docs_env_vars.py
  kpops/utils/cli_commands.py
  kpops/utils/pydantic.py
Labels: type/bug, type/refactor, high priority, area/dependencies

#473 fix(docs): Correct `from.components.<component-name>.type` to input
  docs/docs/resources/pipeline-components/helm-app.yaml
  docs/docs/resources/pipeline-components/kafka-app.yaml
  docs/docs/resources/pipeline-components/kafka-connector.yaml
  docs/docs/resources/pipeline-components/kafka-sink-connector.yaml
  docs/docs/resources/pipeline-components/kubernetes-app.yaml
  docs/docs/resources/pipeline-components/pipeline.yaml
  docs/docs/resources/pipeline-components/sections/from_.yaml
  docs/docs/resources/pipeline-components/streams-app.yaml
  docs/docs/resources/pipeline-defaults/defaults-kafka-app.yaml
  docs/docs/resources/pipeline-defaults/defaults-kafka-connector.yaml
  docs/docs/resources/pipeline-defaults/defaults-kubernetes-app.yaml
  docs/docs/resources/pipeline-defaults/defaults.yaml
Labels: area/documentation

#475 Update Ruff
  hooks/__init__.py
  hooks/gen_docs/gen_docs_components.py
  hooks/gen_docs/gen_docs_env_vars.py
  hooks/gen_schema.py
  kpops/cli/main.py
  kpops/component_handlers/helm_wrapper/model.py
  kpops/component_handlers/schema_handler/schema_provider.py
  kpops/components/base_components/helm_app.py
  kpops/utils/gen_schema.py
  poetry.lock
  pyproject.toml
  tests/cli/test_init.py
  tests/cli/test_registry.py
  tests/cli/test_schema_generation.py
  tests/component_handlers/kafka_connect/test_connect_wrapper.py
  tests/component_handlers/topic/test_proxy_wrapper.py
  tests/component_handlers/topic/test_topic_handler.py
  tests/pipeline/test_components/components.py
  tests/pipeline/test_components_without_schema_handler/components.py
  tests/pipeline/test_generate.py
Labels: area/dependencies

#476 Improve type annotations for parallel pipeline jobs
  kpops/pipeline.py
Labels: type/refactor
