Repository bakdata/kpops, pull requests merged in 2025-01, with the labels that each got.

#574 Represent multiline strings using YAML block style
  kpops/manifests/kubernetes.py
  kpops/utils/yaml.py
  tests/compiler/test_yaml_loading.py
  tests/pipeline/snapshots/test_manifest/test_manifest_command/manifest.yaml
  tests/pipeline/snapshots/test_manifest/test_streams_bootstrap/manifest.yaml
  tests/utils/test_yaml.py
Labels: type/refactor, component/generator, breaking-change

#575 Indent sequence items to follow style recommendations
  hooks/gen_docs/gen_docs_components.py
  kpops/pipeline/__init__.py
  kpops/utils/dict_differ.py
  kpops/utils/yaml.py
  tests/pipeline/snapshots/test_example/test_generate/atm-fraud/pipeline.yaml
  tests/pipeline/snapshots/test_example/test_generate/word-count/pipeline.yaml
  tests/pipeline/snapshots/test_generate/test_default_config/pipeline.yaml
  tests/pipeline/snapshots/test_generate/test_inflate_pipeline/pipeline.yaml
  tests/pipeline/snapshots/test_generate/test_kafka_connect_sink_weave_from_topics/pipeline.yaml
  tests/pipeline/snapshots/test_generate/test_load_pipeline/pipeline.yaml
  tests/pipeline/snapshots/test_generate/test_load_pipeline_with_folder_path/pipeline.yaml
  tests/pipeline/snapshots/test_generate/test_load_pipeline_with_multiple_pipeline_paths/pipeline.yaml
  tests/pipeline/snapshots/test_generate/test_no_input_topic/pipeline.yaml
  tests/pipeline/snapshots/test_generate/test_no_user_defined_components/pipeline.yaml
  tests/pipeline/snapshots/test_generate/test_pipelines_with_envs/pipeline.yaml
  tests/pipeline/snapshots/test_generate/test_read_from_component/pipeline.yaml
  tests/pipeline/snapshots/test_generate/test_streams_bootstrap/pipeline.yaml
  tests/pipeline/snapshots/test_generate/test_substitute_in_component/pipeline.yaml
  tests/pipeline/snapshots/test_generate/test_with_custom_config_with_absolute_defaults_path/pipeline.yaml
  tests/pipeline/snapshots/test_generate/test_with_custom_config_with_relative_defaults_path/pipeline.yaml
  tests/pipeline/snapshots/test_generate/test_with_env_defaults/pipeline.yaml
  tests/pipeline/snapshots/test_manifest/test_deploy_argo_mode/manifest.yaml
  tests/pipeline/snapshots/test_manifest/test_deploy_manifest_mode/manifest.yaml
  tests/pipeline/snapshots/test_manifest/test_manifest_clean_manifest_mode/manifest.yaml
  tests/pipeline/snapshots/test_manifest/test_manifest_clean_python_api/manifest.yaml
  tests/pipeline/snapshots/test_manifest/test_manifest_command/manifest.yaml
  tests/pipeline/snapshots/test_manifest/test_manifest_deploy_python_api/manifest.yaml
  tests/pipeline/snapshots/test_manifest/test_manifest_reset_argo_mode/manifest.yaml
  tests/pipeline/snapshots/test_manifest/test_manifest_reset_manifest_mode/manifest.yaml
  tests/pipeline/snapshots/test_manifest/test_manifest_reset_python_api/manifest.yaml
  tests/pipeline/snapshots/test_manifest/test_streams_bootstrap/manifest.yaml
  tests/pipeline/test_generate.py
  tests/utils/test_yaml.py
Labels: type/refactor, component/generator

#578 Migrate from Poetry to uv
  .bumpversion.cfg
  .github/actions/update-docs/action.yml
  .github/changelog-config.json
  .github/scripts/__init__.py
  .github/scripts/get-dev-version.py
  .github/workflows/_lint-gh-ci.yaml
  .github/workflows/add-issue-ci.yaml
  .github/workflows/ci.yaml
  .github/workflows/publish.yaml
  .github/workflows/release.yaml
  .github/workflows/update-gh-pages.yaml
  .pre-commit-config.yaml
  cliff.toml
  docs/README.md
  docs/docs/developer/contributing.md
  docs/docs/schema/config.json
  docs/docs/schema/defaults.json
  docs/docs/schema/pipeline.json
  docs/docs/user/getting-started/teardown.md
  docs/docs/user/references/cli-commands.md
  justfile
  kpops/cli/main.py
  kpops/components/streams_bootstrap/__init__.py
  kpops/components/streams_bootstrap_v2/__init__.py
  poetry.lock
  pyproject.toml
  tests/component_handlers/helm_wrapper/test_helm_wrapper.py
  tests/component_handlers/kafka_connect/test_connect_handler.py
  tests/component_handlers/kafka_connect/test_connect_wrapper.py
  tests/component_handlers/schema_handler/test_schema_handler.py
  tests/component_handlers/topic/test_proxy_wrapper.py
  tests/component_handlers/topic/test_topic_handler.py
  tests/components/streams_bootstrap/test_producer_app.py
  tests/components/streams_bootstrap/test_streams_app.py
  tests/components/streams_bootstrap/test_streams_bootstrap.py
  tests/components/streams_bootstrap_v2/test_producer_app.py
  tests/components/streams_bootstrap_v2/test_streams_app.py
  tests/components/streams_bootstrap_v2/test_streams_bootstrap.py
  tests/components/test_helm_app.py
  tests/components/test_kafka_sink_connector.py
  tests/components/test_kafka_source_connector.py
  tests/kubernetes/test_pvc_handler.py
  tests/pipeline/resources/dotenv/.env
  tests/pipeline/resources/dotenv/custom.env
  tests/pipeline/test_generate.py
  tests/test_kpops_config.py
  uv.lock
Labels: area/CI, area/dependencies

#583 Fix circular imports when running individual tests
  hooks/gen_docs/gen_docs_components.py
  kpops/api/__init__.py
  kpops/cli/main.py
  kpops/component_handlers/schema_handler/schema_handler.py
  kpops/components/base_components/helm_app.py
  kpops/components/streams_bootstrap/producer/model.py
  kpops/components/streams_bootstrap/producer/producer_app.py
  kpops/components/streams_bootstrap/streams/streams_app.py
  kpops/components/streams_bootstrap_v2/streams/model.py
  kpops/config/__init__.py
  kpops/core/__init__.py
  kpops/core/exception.py
  kpops/core/operation.py
  kpops/core/registry.py
  kpops/manifests/strimzi/kafka_topic.py
  kpops/pipeline/__init__.py
  kpops/utils/gen_schema.py
  tests/api/test_registry.py
  tests/components/streams_bootstrap/test_producer_app.py
  tests/components/streams_bootstrap_v2/test_streams_app.py
  tests/manifests/strimzi/test_kafka_topic.py
  tests/pipeline/test_generate.py
  tests/test_kpops_config.py
Labels: area/tests

#585 Configure Pyright to report import cycles
  kpops/components/streams_bootstrap_v2/producer/producer_app.py
  kpops/components/streams_bootstrap_v2/streams/streams_app.py
  pyproject.toml
Labels: type/refactor

#587 Fail if streams-boostrap v3 model is instantiated with v2 attribute
  kpops/components/streams_bootstrap/model.py
  tests/components/streams_bootstrap/test_streams_bootstrap.py
Labels: component/pipeline-components

#586 Use Pydantic `model_validate` to avoid Pyright warnings
  tests/component_handlers/kubernetes/model.py
  tests/component_handlers/topic/test_utils.py
  tests/components/streams_bootstrap/test_producer_app.py
  tests/components/streams_bootstrap/test_streams_app.py
  tests/components/streams_bootstrap/test_streams_bootstrap.py
  tests/components/streams_bootstrap_v2/test_producer_app.py
  tests/components/streams_bootstrap_v2/test_streams_app.py
  tests/components/test_base_defaults_component.py
  tests/components/test_helm_app.py
  tests/components/test_kafka_sink_connector.py
Labels: type/refactor, area/tests

#591 Fix release commit message
  .github/workflows/python-uv-release.yaml
  cliff.toml
Labels: area/CI

#592 Configure PyPI trusted publishing
  .github/workflows/ci.yaml
  .github/workflows/publish.yaml
  pyproject.toml
Labels: area/CI

#584 Migrate pre-commit hooks to lefthook
  .github/workflows/ci.yaml
  .gitignore
  .pre-commit-config.yaml
  docs/docs/developer/auto-generation.md
  docs/docs/developer/contributing.md
  dprint.json
  hooks/__init__.py
  hooks/gen_docs/gen_docs_components.py
  lefthook.yaml
  pyproject.toml
  uv.lock
Labels: area/CI, area/dependencies

#580 feat: support symbolic linked pipelines to avoid repetition
  kpops/cli/utils.py
  tests/pipeline/resources/pipeline-folders-with-symlinks/pipeline-1/pipeline.yaml
  tests/pipeline/resources/pipeline-folders-with-symlinks/pipeline-2
  tests/pipeline/resources/pipeline-folders-with-symlinks/pipeline-3/pipeline.yaml
  tests/pipeline/resources/pipeline-symlinked/pipeline.yaml
  tests/pipeline/resources/symlinked-folder
  tests/pipeline/test_generate.py
Labels: type/enhancement, component/generator

#596 ci: run lint job only for target Python version on Linux
  .github/workflows/ci.yaml
Labels: area/CI
